# Setup
title:        Middle Tennessee DSA
tagline:      Middle Tennessee's branch of America's fastest growing socialist organization. 
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        https://evasivepangolin.github.io/midtndsa-june/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
